// GENERATED FILE -- DO NOT EDIT BY HAND.
//
// Written by scripts/generate-allowlist.mjs from schema/baseline.sql.
// Re-run it after capture-schema.ps1 rather than editing this.
//
// 41 tables, 445 columns.
// 14 json/jsonb columns, 3 PostgreSQL array columns.

export const TABLE_COLUMNS: Record<string, string[]> = {
  airlines: ['code', 'name', 'first_seen_at', 'last_seen_at'],
  amadeus_session: ['id', 'session_id', 'expires_at', 'updated_at'],
  approval_chain_templates: ['id', 'tmc_id', 'name', 'code', 'description', 'mode', 'quorum', 'tiers', 'version', 'updated_by', 'created_at', 'client_id'],
  approval_tier_approvers: ['client_id', 'template_id', 'tier', 'approver_type', 'approver_user_id', 'min_band_rank', 'assigned_by', 'assigned_at'],
  approvals: ['id', 'client_id', 'booking_id', 'approver_id', 'tier', 'status', 'reason', 'actioned_at', 'escalates_at', 'created_at', 'verdict', 'decision_note', 'chain_template_id'],
  audit_log: ['id', 'client_id', 'tmc_id', 'user_id', 'action', 'entity_type', 'entity_id', 'metadata', 'created_at'],
  band_approval_templates: ['client_id', 'band_code', 'category', 'template_id', 'assigned_at', 'assigned_by'],
  bands: ['id', 'client_id', 'code', 'label', 'rank', 'created_at'],
  bookings: ['id', 'client_id', 'employee_id', 'booking_type', 'status', 'policy_status', 'total_cost', 'provider_order_id', 'pnr', 'itinerary', 'traveler_snapshot', 'created_at', 'updated_at', 'requested_for', 'trip_id', 'provider', 'session_id', 'search_key', 'amadeus_key', 'pricing_key', 'is_ndc', 'ticket_numbers', 'fare_breakdown', 'policy_verdict', 'policy_verdict_detail', 'result_index', 'resolved_deal_codes', 'resolved_fop', 'sell_total', 'commercials', 'share_token'],
  branches: ['id', 'tmc_id', 'name', 'branch_no', 'profit_centre_code', 'gst_number', 'gst_name', 'gst_email', 'gst_contact', 'gst_address_1', 'gst_address_2', 'country', 'gst_state', 'gst_city', 'gst_zip', 'iata_number', 'office_id', 'is_head_office', 'status', 'created_by', 'created_at', 'updated_at'],
  bucket_clients: ['bucket_id', 'client_id', 'created_at'],
  buckets: ['id', 'tmc_id', 'name', 'code', 'description', 'created_by', 'created_at'],
  client_default_approval_templates: ['client_id', 'category', 'template_id', 'assigned_at', 'assigned_by'],
  client_groups: ['id', 'tmc_id', 'name', 'city', 'country', 'created_at', 'group_code', 'contact_first_name', 'contact_last_name', 'contact_email', 'contact_mobile', 'bill_to_address_1', 'bill_to_address_2', 'bill_to_state', 'bill_to_pincode'],
  client_gst_registrations: ['id', 'client_id', 'gstin', 'gst_holder', 'email', 'contact', 'address_1', 'address_2', 'city', 'state', 'country', 'zip', 'registration_date', 'valid_from', 'valid_to', 'cost_centre_id', 'is_primary', 'created_at'],
  client_mandatory_info: ['id', 'client_id', 'code', 'description', 'type', 'gds_entry', 'value_prefix', 'is_mandatory', 'created_at'],
  client_policy_groups: ['client_id', 'policy_group_id', 'assigned_at', 'assigned_by'],
  clients: ['id', 'tmc_id', 'name', 'status', 'settings', 'created_at', 'setup_completed', 'setup_completed_at', 'size', 'currency', 'country', 'timezone', 'booking_mode', 'client_group_id', 'managed_by', 'registered_address', 'industry', 'primary_contact_phone', 'branch_id', 'client_code', 'sap_customer_code', 'sap_group_code', 'email', 'phone', 'address_1', 'address_2', 'city', 'state', 'pincode', 'collections_name', 'collections_email', 'collections_mobile', 'booking_activation', 'hold_activation', 'dom_ticketing', 'intl_ticketing', 'hold_auto_issue', 'sbt_ticketing', 'policy_controlling', 'personal_bookings_allowed', 'agency_fop_allowed', 'corporate_fop_allowed', 'discount_active', 'processing_fee_active', 'air_approval_mode', 'hotel_approval_mode', 'bta_cta_allowed', 'bta_cta_manual_allowed', 'fop_priority', 'markup_active'],
  commercial_rule_assignments: ['id', 'tmc_id', 'rule_id', 'kind', 'client_id', 'client_group_id', 'bucket_id', 'created_by', 'created_at'],
  commercial_rules: ['id', 'tmc_id', 'kind', 'category_id', 'airline_code', 'cabin', 'rbd_spec', 'fare_type', 'calc_type', 'calc_on', 'rate', 'calc_basis', 'exclude_tax_codes', 'include_ssr', 'valid_from', 'valid_to', 'active', 'notes', 'created_by', 'created_at', 'updated_at'],
  cost_centres: ['id', 'client_id', 'code', 'name', 'created_at'],
  deal_code_assignments: ['id', 'tmc_id', 'deal_code_id', 'kind', 'client_id', 'client_group_id', 'bucket_id', 'created_by', 'created_at'],
  deal_code_categories: ['id', 'tmc_id', 'code', 'label', 'active', 'created_at'],
  deal_code_category_types: ['category_id', 'code_type', 'allowed'],
  deal_codes: ['id', 'tmc_id', 'category_id', 'airline_code', 'code', 'code_type', 'flight_spec', 'sales_from', 'sales_to', 'travel_from', 'travel_to', 'active', 'notes', 'created_by', 'created_at', 'updated_at'],
  employee_approval_templates: ['employee_id', 'category', 'template_id', 'assigned_at', 'assigned_by'],
  employee_client_access: ['employee_id', 'client_id', 'granted_by', 'granted_at'],
  employee_permissions: ['employee_id', 'permission_key', 'granted_by', 'granted_at'],
  employees: ['id', 'client_id', 'tmc_id', 'band_id', 'manager_id', 'full_name', 'email', 'role', 'department', 'cost_centre', 'band_code', 'band_rank', 'traveler_profile', 'status', 'created_at', 'invited_by', 'invited_at', 'onboarding_method', 'first_login_completed', 'client_group_id', 'auth_user_id', 'top_of_hierarchy', 'designation', 'branch_id'],
  fop_assignments: ['id', 'tmc_id', 'fop_id', 'kind', 'client_id', 'client_group_id', 'bucket_id', 'created_by', 'created_at', 'is_active'],
  fop_gds_entries: ['id', 'tmc_id', 'code', 'label', 'active', 'created_at'],
  fop_payment_types: ['id', 'tmc_id', 'code', 'label', 'requires_card', 'active', 'created_at'],
  forms_of_payment: ['id', 'tmc_id', 'label', 'fop_type', 'payer', 'card_type', 'last4', 'expiry_month', 'expiry_year', 'gds_alias', 'branch_id', 'owner_client_id', 'owner_employee_id', 'airline_code', 'rbd_spec', 'active', 'notes', 'created_by', 'created_at', 'updated_at', 'fop_code', 'gds_entry_id', 'payment_type_id', 'is_default'],
  platform_admins: ['user_id', 'email', 'note', 'created_at'],
  policy_group_band_ranks: ['policy_group_id', 'band_rank'],
  policy_groups: ['id', 'name', 'description', 'created_at', 'tmc_id', 'code'],
  policy_rules: ['id', 'client_id', 'tmc_id', 'band_id', 'travel_type', 'limit_key', 'limit_value', 'locked', 'version', 'updated_by', 'created_at', 'policy_group_id', 'deleted_at', 'band_code', 'limit_bool'],
  price_quotes: ['id', 'client_id', 'employee_id', 'amadeus_key', 'reference_no', 'pricing_key', 'provider', 'result_index', 'airline_components', 'commercials', 'sell_total', 'created_at', 'expires_at'],
  tmcs: ['id', 'name', 'status', 'settings', 'created_at'],
  trip_expenses: ['id', 'trip_id', 'client_id', 'created_by', 'expense_type', 'amount', 'currency', 'description', 'receipt_url', 'expense_date', 'created_at', 'updated_at'],
  trips: ['id', 'client_id', 'created_by', 'name', 'description', 'travel_date', 'status', 'created_at', 'updated_at'],
}

// The category the shim branches on when binding a value. See normaliseType in
// the generator, and coerceForColumn in builder.ts.
export type ColumnKind =
  | 'json' | 'array' | 'numeric' | 'integer' | 'boolean'
  | 'timestamptz' | 'date' | 'uuid' | 'text'

export const COLUMN_TYPES: Record<string, Record<string, ColumnKind>> = {
  airlines: { code: 'text', name: 'text', first_seen_at: 'timestamptz', last_seen_at: 'timestamptz' },
  amadeus_session: { id: 'integer', session_id: 'text', expires_at: 'timestamptz', updated_at: 'timestamptz' },
  approval_chain_templates: { id: 'uuid', tmc_id: 'uuid', name: 'text', code: 'text', description: 'text', mode: 'text', quorum: 'text', tiers: 'json', version: 'integer', updated_by: 'uuid', created_at: 'timestamptz', client_id: 'uuid' },
  approval_tier_approvers: { client_id: 'uuid', template_id: 'uuid', tier: 'integer', approver_type: 'text', approver_user_id: 'uuid', min_band_rank: 'integer', assigned_by: 'uuid', assigned_at: 'timestamptz' },
  approvals: { id: 'uuid', client_id: 'uuid', booking_id: 'uuid', approver_id: 'uuid', tier: 'integer', status: 'text', reason: 'text', actioned_at: 'timestamptz', escalates_at: 'timestamptz', created_at: 'timestamptz', verdict: 'text', decision_note: 'text', chain_template_id: 'uuid' },
  audit_log: { id: 'uuid', client_id: 'uuid', tmc_id: 'uuid', user_id: 'uuid', action: 'text', entity_type: 'text', entity_id: 'uuid', metadata: 'json', created_at: 'timestamptz' },
  band_approval_templates: { client_id: 'uuid', band_code: 'text', category: 'text', template_id: 'uuid', assigned_at: 'timestamptz', assigned_by: 'uuid' },
  bands: { id: 'uuid', client_id: 'uuid', code: 'text', label: 'text', rank: 'integer', created_at: 'timestamptz' },
  bookings: { id: 'uuid', client_id: 'uuid', employee_id: 'uuid', booking_type: 'text', status: 'text', policy_status: 'text', total_cost: 'numeric', provider_order_id: 'text', pnr: 'text', itinerary: 'json', traveler_snapshot: 'json', created_at: 'timestamptz', updated_at: 'timestamptz', requested_for: 'uuid', trip_id: 'uuid', provider: 'text', session_id: 'text', search_key: 'text', amadeus_key: 'text', pricing_key: 'text', is_ndc: 'boolean', ticket_numbers: 'array', fare_breakdown: 'json', policy_verdict: 'text', policy_verdict_detail: 'json', result_index: 'text', resolved_deal_codes: 'json', resolved_fop: 'json', sell_total: 'numeric', commercials: 'json', share_token: 'text' },
  branches: { id: 'uuid', tmc_id: 'uuid', name: 'text', branch_no: 'text', profit_centre_code: 'text', gst_number: 'text', gst_name: 'text', gst_email: 'text', gst_contact: 'text', gst_address_1: 'text', gst_address_2: 'text', country: 'text', gst_state: 'text', gst_city: 'text', gst_zip: 'text', iata_number: 'text', office_id: 'text', is_head_office: 'boolean', status: 'text', created_by: 'uuid', created_at: 'timestamptz', updated_at: 'timestamptz' },
  bucket_clients: { bucket_id: 'uuid', client_id: 'uuid', created_at: 'timestamptz' },
  buckets: { id: 'uuid', tmc_id: 'uuid', name: 'text', code: 'text', description: 'text', created_by: 'uuid', created_at: 'timestamptz' },
  client_default_approval_templates: { client_id: 'uuid', category: 'text', template_id: 'uuid', assigned_at: 'timestamptz', assigned_by: 'uuid' },
  client_groups: { id: 'uuid', tmc_id: 'uuid', name: 'text', city: 'text', country: 'text', created_at: 'timestamptz', group_code: 'text', contact_first_name: 'text', contact_last_name: 'text', contact_email: 'text', contact_mobile: 'text', bill_to_address_1: 'text', bill_to_address_2: 'text', bill_to_state: 'text', bill_to_pincode: 'text' },
  client_gst_registrations: { id: 'uuid', client_id: 'uuid', gstin: 'text', gst_holder: 'text', email: 'text', contact: 'text', address_1: 'text', address_2: 'text', city: 'text', state: 'text', country: 'text', zip: 'text', registration_date: 'date', valid_from: 'date', valid_to: 'date', cost_centre_id: 'uuid', is_primary: 'boolean', created_at: 'timestamptz' },
  client_mandatory_info: { id: 'uuid', client_id: 'uuid', code: 'text', description: 'text', type: 'text', gds_entry: 'text', value_prefix: 'text', is_mandatory: 'boolean', created_at: 'timestamptz' },
  client_policy_groups: { client_id: 'uuid', policy_group_id: 'uuid', assigned_at: 'timestamptz', assigned_by: 'uuid' },
  clients: { id: 'uuid', tmc_id: 'uuid', name: 'text', status: 'text', settings: 'json', created_at: 'timestamptz', setup_completed: 'boolean', setup_completed_at: 'timestamptz', size: 'text', currency: 'text', country: 'text', timezone: 'text', booking_mode: 'text', client_group_id: 'uuid', managed_by: 'uuid', registered_address: 'text', industry: 'text', primary_contact_phone: 'text', branch_id: 'uuid', client_code: 'text', sap_customer_code: 'text', sap_group_code: 'text', email: 'text', phone: 'text', address_1: 'text', address_2: 'text', city: 'text', state: 'text', pincode: 'text', collections_name: 'text', collections_email: 'text', collections_mobile: 'text', booking_activation: 'boolean', hold_activation: 'boolean', dom_ticketing: 'boolean', intl_ticketing: 'boolean', hold_auto_issue: 'boolean', sbt_ticketing: 'boolean', policy_controlling: 'boolean', personal_bookings_allowed: 'boolean', agency_fop_allowed: 'boolean', corporate_fop_allowed: 'boolean', discount_active: 'boolean', processing_fee_active: 'boolean', air_approval_mode: 'text', hotel_approval_mode: 'text', bta_cta_allowed: 'boolean', bta_cta_manual_allowed: 'boolean', fop_priority: 'array', markup_active: 'boolean' },
  commercial_rule_assignments: { id: 'uuid', tmc_id: 'uuid', rule_id: 'uuid', kind: 'text', client_id: 'uuid', client_group_id: 'uuid', bucket_id: 'uuid', created_by: 'uuid', created_at: 'timestamptz' },
  commercial_rules: { id: 'uuid', tmc_id: 'uuid', kind: 'text', category_id: 'uuid', airline_code: 'text', cabin: 'text', rbd_spec: 'text', fare_type: 'text', calc_type: 'text', calc_on: 'text', rate: 'numeric', calc_basis: 'text', exclude_tax_codes: 'array', include_ssr: 'boolean', valid_from: 'date', valid_to: 'date', active: 'boolean', notes: 'text', created_by: 'uuid', created_at: 'timestamptz', updated_at: 'timestamptz' },
  cost_centres: { id: 'uuid', client_id: 'uuid', code: 'text', name: 'text', created_at: 'timestamptz' },
  deal_code_assignments: { id: 'uuid', tmc_id: 'uuid', deal_code_id: 'uuid', kind: 'text', client_id: 'uuid', client_group_id: 'uuid', bucket_id: 'uuid', created_by: 'uuid', created_at: 'timestamptz' },
  deal_code_categories: { id: 'uuid', tmc_id: 'uuid', code: 'text', label: 'text', active: 'boolean', created_at: 'timestamptz' },
  deal_code_category_types: { category_id: 'uuid', code_type: 'text', allowed: 'boolean' },
  deal_codes: { id: 'uuid', tmc_id: 'uuid', category_id: 'uuid', airline_code: 'text', code: 'text', code_type: 'text', flight_spec: 'text', sales_from: 'date', sales_to: 'date', travel_from: 'date', travel_to: 'date', active: 'boolean', notes: 'text', created_by: 'uuid', created_at: 'timestamptz', updated_at: 'timestamptz' },
  employee_approval_templates: { employee_id: 'uuid', category: 'text', template_id: 'uuid', assigned_at: 'timestamptz', assigned_by: 'uuid' },
  employee_client_access: { employee_id: 'uuid', client_id: 'uuid', granted_by: 'uuid', granted_at: 'timestamptz' },
  employee_permissions: { employee_id: 'uuid', permission_key: 'text', granted_by: 'uuid', granted_at: 'timestamptz' },
  employees: { id: 'uuid', client_id: 'uuid', tmc_id: 'uuid', band_id: 'uuid', manager_id: 'uuid', full_name: 'text', email: 'text', role: 'text', department: 'text', cost_centre: 'text', band_code: 'text', band_rank: 'integer', traveler_profile: 'json', status: 'text', created_at: 'timestamptz', invited_by: 'uuid', invited_at: 'timestamptz', onboarding_method: 'text', first_login_completed: 'boolean', client_group_id: 'uuid', auth_user_id: 'uuid', top_of_hierarchy: 'boolean', designation: 'text', branch_id: 'uuid' },
  fop_assignments: { id: 'uuid', tmc_id: 'uuid', fop_id: 'uuid', kind: 'text', client_id: 'uuid', client_group_id: 'uuid', bucket_id: 'uuid', created_by: 'uuid', created_at: 'timestamptz', is_active: 'boolean' },
  fop_gds_entries: { id: 'uuid', tmc_id: 'uuid', code: 'text', label: 'text', active: 'boolean', created_at: 'timestamptz' },
  fop_payment_types: { id: 'uuid', tmc_id: 'uuid', code: 'text', label: 'text', requires_card: 'boolean', active: 'boolean', created_at: 'timestamptz' },
  forms_of_payment: { id: 'uuid', tmc_id: 'uuid', label: 'text', fop_type: 'text', payer: 'text', card_type: 'text', last4: 'text', expiry_month: 'integer', expiry_year: 'integer', gds_alias: 'text', branch_id: 'uuid', owner_client_id: 'uuid', owner_employee_id: 'uuid', airline_code: 'text', rbd_spec: 'text', active: 'boolean', notes: 'text', created_by: 'uuid', created_at: 'timestamptz', updated_at: 'timestamptz', fop_code: 'text', gds_entry_id: 'uuid', payment_type_id: 'uuid', is_default: 'boolean' },
  platform_admins: { user_id: 'uuid', email: 'text', note: 'text', created_at: 'timestamptz' },
  policy_group_band_ranks: { policy_group_id: 'uuid', band_rank: 'integer' },
  policy_groups: { id: 'uuid', name: 'text', description: 'text', created_at: 'timestamptz', tmc_id: 'uuid', code: 'text' },
  policy_rules: { id: 'uuid', client_id: 'uuid', tmc_id: 'uuid', band_id: 'uuid', travel_type: 'text', limit_key: 'text', limit_value: 'numeric', locked: 'boolean', version: 'integer', updated_by: 'uuid', created_at: 'timestamptz', policy_group_id: 'uuid', deleted_at: 'timestamptz', band_code: 'text', limit_bool: 'boolean' },
  price_quotes: { id: 'uuid', client_id: 'uuid', employee_id: 'uuid', amadeus_key: 'text', reference_no: 'text', pricing_key: 'text', provider: 'text', result_index: 'text', airline_components: 'json', commercials: 'json', sell_total: 'numeric', created_at: 'timestamptz', expires_at: 'timestamptz' },
  tmcs: { id: 'uuid', name: 'text', status: 'text', settings: 'json', created_at: 'timestamptz' },
  trip_expenses: { id: 'uuid', trip_id: 'uuid', client_id: 'uuid', created_by: 'uuid', expense_type: 'text', amount: 'numeric', currency: 'text', description: 'text', receipt_url: 'text', expense_date: 'date', created_at: 'timestamptz', updated_at: 'timestamptz' },
  trips: { id: 'uuid', client_id: 'uuid', created_by: 'uuid', name: 'text', description: 'text', travel_date: 'date', status: 'text', created_at: 'timestamptz', updated_at: 'timestamptz' },
}
