// GENERATED by scripts/build-airports.mjs from OurAirports (public domain).
// Do not edit by hand: rebuild, and add a migration with the same data.
//
// Every Indian airport with an IATA code (164). A trip is domestic only
// when every leg is between two of these; see app/lib/rule-engine/classifyTrip.ts.

export const INDIAN_AIRPORT_CODES: readonly string[] = [
  'AGR', 'AGX', 'AHA', 'AIP', 'AJL', 'AKD', 'AMD', 'ATQ', 'AVR', 'AYJ', 'AZH', 'BBI',
  'BDQ', 'BEK', 'BEP', 'BHJ', 'BHO', 'BHU', 'BKB', 'BLR', 'BOM', 'BPM', 'BUP', 'CBD',
  'CCJ', 'CCU', 'CDP', 'CJB', 'CNN', 'COH', 'COK', 'CWK', 'DBD', 'DBR', 'DED', 'DEL',
  'DEP', 'DGH', 'DHM', 'DIB', 'DIU', 'DMU', 'DXN', 'GAU', 'GAY', 'GBI', 'GDB', 'GOI',
  'GOP', 'GOX', 'GUX', 'GWL', 'HBX', 'HDO', 'HGI', 'HJR', 'HRH', 'HSR', 'HSS', 'HWR',
  'HYD', 'IDR', 'IMF', 'ISK', 'IXA', 'IXB', 'IXC', 'IXD', 'IXE', 'IXG', 'IXH', 'IXI',
  'IXJ', 'IXK', 'IXL', 'IXM', 'IXN', 'IXP', 'IXQ', 'IXR', 'IXS', 'IXT', 'IXU', 'IXV',
  'IXW', 'IXX', 'IXY', 'IXZ', 'JAI', 'JDH', 'JGA', 'JGB', 'JLG', 'JLR', 'JRG', 'JRH',
  'JSA', 'KBK', 'KJB', 'KLH', 'KNU', 'KQH', 'KTU', 'KUU', 'LDA', 'LKO', 'LTU', 'LUH',
  'MAA', 'MYQ', 'MZS', 'MZU', 'NAG', 'NDC', 'NMB', 'NMI', 'NVY', 'PAB', 'PAT', 'PBD',
  'PGH', 'PNQ', 'PNY', 'PUT', 'PYB', 'PYG', 'RAJ', 'RDP', 'REW', 'RGH', 'RJA', 'RJI',
  'RMD', 'RPR', 'RQY', 'RRK', 'RTC', 'RUP', 'SAG', 'SDW', 'SHL', 'SLV', 'SSE', 'STV',
  'SWN', 'SXR', 'SXV', 'TCR', 'TEI', 'TEZ', 'TIR', 'TJV', 'TNI', 'TRV', 'TRZ', 'UDR',
  'UKE', 'VDY', 'VGA', 'VNS', 'VSV', 'VTZ', 'WGC', 'ZER',
]
